apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-vente-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-vente-service
  template:
    metadata:
      labels:
        app: store-vente-service
    spec:
      containers:
        - name: store-vente-service
          image: touijeroussama/store-vente-service-img  # Utilisez votre image Docker
          ports:
            - containerPort: 8082
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://store-discovery-service:8761/eureka"
            - name: CONFIG_SERVICE_URL
              value: "http://store-config-service:9999"
            - name: ACHETEUR_SERVICE_URL
              value: "http://store-acheteur-service:8081"

---
apiVersion: v1
kind: Service
metadata:
  name: store-vente-service
spec:
  selector:
    app: store-vente-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer