apiVersion: apps/v1
kind: Deployment
metadata:
  name: produit-service
  namespace: my-nia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: produit-service
  template:
    metadata:
      labels:
        app: produit-service
    spec:
      containers:
        - name: produit-service
          image: touijeroussama/store-produit-service-img
          ports:
            - containerPort: 8079
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://store-discovery-service:8761/eureka"

---
apiVersion: v1
kind: Service
metadata:
  name: produit-service
  namespace: my-nia
spec:
  selector:
    app: produit-service
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
  type: LoadBalancer

