apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-acheteur-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-acheteur-service
  template:
    metadata:
      labels:
        app: store-acheteur-service
    spec:
      containers:
        - name: store-acheteur-service
          image: touijeroussama/store-acheteur-service-img  # Utilisez votre image Docker
          ports:
            - containerPort: 8081
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://store-discovery-service:8761/eureka"
            - name: CONFIG_SERVICE_URL
              value: "http://store-config-service:9999"
            - name: PRODUIT_SERVICE_URL
              value: "http://store-produit-service:8079"
---
apiVersion: v1
kind: Service
metadata:
  name: store-acheteur-service
spec:
  selector:
    app: store-acheteur-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer