apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-gateway-service
  template:
    metadata:
      labels:
        app: store-gateway-service
    spec:
      containers:
        - name: store-gateway-service
          image: touijeroussama/store-gateway-service-img  # Utilisez votre image Docker
          ports:
            - containerPort: 8888
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://store-discovery-service:8761/eureka"
            - name: CONFIG_SERVICE_URL
              value: "http://store-config-service:9999"
---
apiVersion: v1
kind: Service
metadata:
  name: store-gateway-service
spec:
  selector:
    app: store-gateway-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
