apiVersion: v1
kind: Namespace
metadata:
  name: my-nia  # Remplacez par le nom de votre namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vente-service
  namespace: my-nia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vente-service
  template:
    metadata:
      labels:
        app: vente-service
    spec:
      containers:
        - name: vente-service
          image: touijeroussama/store-vente-service-img
          ports:
            - containerPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: produit-service
  namespace: my-nia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: produit-service
  template:
    metadata:
      labels:
        app: produit-service
    spec:
      containers:
        - name: produit-service
          image: touijeroussama/store-produit-service-img
          ports:
            - containerPort: 8079

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: my-nia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: touijeroussama/store-gateway-service-img
          ports:
            - containerPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: my-nia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: touijeroussama/store-discovery-service-img
          ports:
            - containerPort: 8761

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: my-nia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: touijeroussama/store-config-service-img
          ports:
            - containerPort: 9999

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: acheteur-service
  namespace: my-nia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acheteur-service
  template:
    metadata:
      labels:
        app: acheteur-service
    spec:
      containers:
        - name: acheteur-service
          image: touijeroussama/store-acheteur-service-img
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: vente-service
  namespace: my-nia
spec:
  selector:
    app: vente-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: produit-service
  namespace: my-nia
spec:
  selector:
    app: produit-service
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: my-nia
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: my-nia
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: my-nia
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: acheteur-service
  namespace: my-nia
spec:
  selector:
    app: acheteur-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

# Répétez cela pour les autres services (produit, gateway, discovery, config, acheteur)
