apiVersion: apps/v1
kind: Service
metadata:
  name: produit-service-service
spec:
  selector:
    app: produit-service-app   # Corrected label here
  ports:
    - protocol: 'TCP'
      port: 8079
      targetPort: 8079
  type: LoadBalancer
