apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app   # Corrected label here
  template:
    metadata:
      labels:
        app: gateway-service-app   # Matching label here
    spec:
      containers:
        - name: store-gateway-service-container
          image: touijeroussama/store-gateway-service-img
