apiVersion: apps/v1
kind: Service
metadata:
  name: gateway-service-service
spec:
  selector:
    app: gateway-service-app   # Corrected label here
  ports:
    - protocol: 'TCP'
      port: 8888
      targetPort: 8888
  type: LoadBalancer
