apiVersion: apps/v1
kind: Deployment
metadata:
  name: acheteur-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acheteur-service-app   # Corrected label here
  template:
    metadata:
      labels:
        app: acheteur-service-app   # Matching label here
    spec:
      containers:
        - name: store-acheteur-service-container
          image: touijeroussama/store-acheteur-service-img
