apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service-app
  template:
    metadata:
      labels:
        app: config-service-app
    spec:
      containers:
        - name: store-config-service-container
          image: touijeroussama/store-config-service-img
