apiVersion: apps/v1
kind: Deployment
metadata:
  name: vente-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vente-service-app   # Corrected label here
  template:
    metadata:
      labels:
        app: vente-service-app   # Matching label here
    spec:
      containers:
        - name: store-vente-service-container
          image: touijeroussama/store-vente-service-img
