apiVersion: apps/v1
kind: Service
metadata:
  name: vente-service-service
spec:
  selector:
    app: vente-service-app   # Corrected label here
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: LoadBalancer
